/**
 * @fileoverview Service layer for the sovereign GROUP site builder (Phase G / P-G4).
 *
 * Centralizes owner authorization, server-side site generation, version
 * snapshotting, and publish so API/UI callers never reimplement any of it. Owner
 * identity is ALWAYS derived server-side:
 *
 *   - Owner resolution uses the group's session model (the SAME gate the design
 *     suite uses): {@link resolveAuthenticatedUserId} derives the caller from
 *     `auth()`, and a requested `targetAgentId` only NAMES a group whose site the
 *     caller may manage — authorized via {@link hasGroupWriteAccess}, never
 *     trusted as the owner. Client-supplied owner is never trusted.
 *
 *   - Site files are generated by the pure {@link buildSiteFiles} from the
 *     owner's Resources (REA model). Generation is server-side to keep client
 *     bundles thin.
 *
 *   - Snapshots persist to `site_versions` (fleet-portable, matching the global +
 *     person app shape); the live state persists to `site_publications`.
 *
 * Sovereign adaptation: unlike global, this group instance has no A7
 * opaque-credential `user_connections` DNS connector lane, so the custom-domain
 * DNS-write path (global's `bindCustomDomain` / `/api/builder/domain`) is
 * intentionally NOT ported here. The `site_publications` domain columns are kept
 * (schema parity / fleet-portable snapshots) but stay `unbound`.
 */
import { and, desc, eq, sql } from "drizzle-orm";

import { db } from "@/db";
import {
  agents,
  resources as resourcesTable,
  sitePublications,
  siteVersions,
  type SitePublication,
  type SiteVersion,
} from "@/db/schema";
import {
  resolveAuthenticatedUserId,
  hasGroupWriteAccess,
} from "@/app/actions/resource-creation/helpers";
import {
  buildSiteFiles,
  fileCount,
  resolveThemePreset,
  type BuildSiteOptions,
  type SiteFiles,
  type SiteOwner,
  type SiteResource,
} from "@/lib/builder/site-model";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Snapshot triggers persisted in `site_versions.trigger`. */
export const SITE_TRIGGER_MANUAL = "manual";
export const SITE_TRIGGER_PUBLISH = "publish";
export const SITE_TRIGGER_SAVE = "save";

/** Domain binding statuses persisted in `site_publications.domain_status`. */
export const DOMAIN_STATUS_UNBOUND = "unbound";

/** Max resources loaded per owner when generating a site. */
const MAX_OWNER_RESOURCES = 500;

// ---------------------------------------------------------------------------
// Owner loading
// ---------------------------------------------------------------------------

/** Loads the owner agent as a {@link SiteOwner} for generation. */
async function loadOwner(agentId: string): Promise<SiteOwner> {
  const [row] = await db
    .select({
      id: agents.id,
      name: agents.name,
      type: agents.type,
      description: agents.description,
      image: agents.image,
      metadata: agents.metadata,
    })
    .from(agents)
    .where(eq(agents.id, agentId))
    .limit(1);
  if (!row) {
    throw new SiteServiceError("OWNER_NOT_FOUND", `No agent found for owner ${agentId}.`);
  }
  return {
    id: row.id,
    name: row.name,
    type: row.type,
    description: row.description,
    image: row.image,
    metadata: (row.metadata as Record<string, unknown> | null) ?? {},
  };
}

/** Loads the owner's non-deleted resources as {@link SiteResource}s. */
async function loadOwnerResources(agentId: string): Promise<SiteResource[]> {
  const rows = await db
    .select({
      id: resourcesTable.id,
      name: resourcesTable.name,
      type: resourcesTable.type,
      description: resourcesTable.description,
      content: resourcesTable.content,
      url: resourcesTable.url,
      createdAt: resourcesTable.createdAt,
    })
    .from(resourcesTable)
    .where(and(eq(resourcesTable.ownerId, agentId), sql`${resourcesTable.deletedAt} IS NULL`))
    .orderBy(desc(resourcesTable.createdAt))
    .limit(MAX_OWNER_RESOURCES);

  return rows.map((row) => ({
    id: row.id,
    name: row.name,
    type: row.type,
    description: row.description,
    content: row.content,
    url: row.url,
    createdAt: row.createdAt ? row.createdAt.toISOString() : null,
  }));
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

/** Specific error for site-service failures. */
export class SiteServiceError extends Error {
  public readonly code: string;
  constructor(code: string, message: string) {
    super(message);
    this.name = "SiteServiceError";
    this.code = code;
  }
}

// ---------------------------------------------------------------------------
// Generation
// ---------------------------------------------------------------------------

/**
 * Generates (but does not persist) the static-site files for an owner from its
 * current Resources. Pure-ish: reads the DB, delegates to the pure generator.
 */
export async function generateSiteFiles(
  agentId: string,
  options: BuildSiteOptions = {},
): Promise<SiteFiles> {
  const [owner, ownerResources] = await Promise.all([loadOwner(agentId), loadOwnerResources(agentId)]);
  return buildSiteFiles(owner, ownerResources, options);
}

// ---------------------------------------------------------------------------
// Versioning
// ---------------------------------------------------------------------------

/** Public projection of a version snapshot (no file bodies). */
export interface PublicSiteVersion {
  id: string;
  versionNumber: number;
  commitMessage: string | null;
  trigger: string;
  fileCount: number;
  createdAt: string;
}

/** Maps a row to its client-safe projection. */
function toPublicVersion(row: SiteVersion): PublicSiteVersion {
  return {
    id: row.id,
    versionNumber: row.versionNumber,
    commitMessage: row.commitMessage,
    trigger: row.trigger,
    fileCount: row.filesSnapshot ? Object.keys(row.filesSnapshot).length : 0,
    createdAt: row.createdAt.toISOString(),
  };
}

/** Lists an owner's version snapshots, newest first. */
export async function listSiteVersions(agentId: string, limit = 50): Promise<PublicSiteVersion[]> {
  const rows = await db
    .select()
    .from(siteVersions)
    .where(eq(siteVersions.agentId, agentId))
    .orderBy(desc(siteVersions.versionNumber))
    .limit(limit);
  return rows.map(toPublicVersion);
}

/**
 * Creates a new version snapshot of the provided files for an owner,
 * auto-assigning the next per-owner version number.
 *
 * @throws {SiteServiceError} When `files` is empty.
 */
export async function createSiteVersion(
  agentId: string,
  files: SiteFiles,
  options: { commitMessage?: string | null; trigger?: string } = {},
): Promise<PublicSiteVersion> {
  if (!files || fileCount(files) === 0) {
    throw new SiteServiceError("EMPTY_FILES", "Cannot snapshot an empty site.");
  }
  const [{ maxVersion } = { maxVersion: 0 }] = await db
    .select({ maxVersion: sql<number>`COALESCE(MAX(${siteVersions.versionNumber}), 0)` })
    .from(siteVersions)
    .where(eq(siteVersions.agentId, agentId));
  const nextVersion = (maxVersion ?? 0) + 1;

  const [inserted] = await db
    .insert(siteVersions)
    .values({
      agentId,
      versionNumber: nextVersion,
      commitMessage: options.commitMessage ?? null,
      filesSnapshot: files,
      trigger: options.trigger ?? SITE_TRIGGER_MANUAL,
    })
    .returning();
  return toPublicVersion(inserted);
}

/** Returns the full files snapshot of a specific version (for restore/serve). */
export async function getSiteVersionFiles(
  agentId: string,
  versionId: string,
): Promise<SiteFiles | null> {
  const [row] = await db
    .select()
    .from(siteVersions)
    .where(and(eq(siteVersions.id, versionId), eq(siteVersions.agentId, agentId)))
    .limit(1);
  return row?.filesSnapshot ?? null;
}

// ---------------------------------------------------------------------------
// Publication state
// ---------------------------------------------------------------------------

/** Public projection of an owner's publication state. */
export interface PublicSitePublication {
  agentId: string;
  publishedVersionId: string | null;
  publishedVersionNumber: number | null;
  theme: string | null;
  customDomain: string | null;
  domainProvider: string | null;
  domainStatus: string;
  domainError: string | null;
  publishedAt: string | null;
}

/** Maps a publication row to its client-safe projection. */
function toPublicPublication(row: SitePublication): PublicSitePublication {
  return {
    agentId: row.agentId,
    publishedVersionId: row.publishedVersionId,
    publishedVersionNumber: row.publishedVersionNumber,
    theme: row.theme,
    customDomain: row.customDomain,
    domainProvider: row.domainProvider,
    domainStatus: row.domainStatus,
    domainError: row.domainError,
    publishedAt: row.publishedAt ? row.publishedAt.toISOString() : null,
  };
}

/** Reads the current publication state, or null when never published. */
export async function getSitePublication(agentId: string): Promise<PublicSitePublication | null> {
  const [row] = await db
    .select()
    .from(sitePublications)
    .where(eq(sitePublications.agentId, agentId))
    .limit(1);
  return row ? toPublicPublication(row) : null;
}

/** Upserts the owner's publication row with a partial patch. */
async function upsertPublication(
  agentId: string,
  patch: Partial<Omit<SitePublication, "id" | "agentId" | "createdAt">>,
): Promise<SitePublication> {
  const [row] = await db
    .insert(sitePublications)
    .values({ agentId, ...patch, updatedAt: new Date() })
    .onConflictDoUpdate({
      target: sitePublications.agentId,
      set: { ...patch, updatedAt: new Date() },
    })
    .returning();
  return row;
}

// ---------------------------------------------------------------------------
// Publish
// ---------------------------------------------------------------------------

/** Result of a publish operation. */
export interface PublishResult {
  version: PublicSiteVersion;
  publication: PublicSitePublication;
}

/**
 * Generates the current site from the owner's Resources, snapshots it as a new
 * version, and marks it live in `site_publications`. The single source of truth
 * for "publish".
 */
export async function publishSite(
  agentId: string,
  options: BuildSiteOptions & { commitMessage?: string | null } = {},
): Promise<PublishResult> {
  const files = await generateSiteFiles(agentId, options);
  const version = await createSiteVersion(agentId, files, {
    commitMessage: options.commitMessage ?? "Published site",
    trigger: SITE_TRIGGER_PUBLISH,
  });
  const publicationRow = await upsertPublication(agentId, {
    publishedVersionId: version.id,
    publishedVersionNumber: version.versionNumber,
    theme: resolveThemePreset(options.theme),
    publishedAt: new Date(),
  });
  return { version, publication: toPublicPublication(publicationRow) };
}

/**
 * Publishes an EXPLICIT file map as the new live version — the builder
 * assistant's deploy path (its edit loop produces raw files; regenerating from
 * resources like {@link publishSite} would discard them). Same snapshot +
 * publication mechanics; theme is left untouched.
 */
export async function publishSiteFiles(
  agentId: string,
  files: SiteFiles,
  commitMessage: string | null = "Published from the builder assistant",
): Promise<PublishResult> {
  const version = await createSiteVersion(agentId, files, {
    commitMessage,
    trigger: SITE_TRIGGER_PUBLISH,
  });
  const publicationRow = await upsertPublication(agentId, {
    publishedVersionId: version.id,
    publishedVersionNumber: version.versionNumber,
    publishedAt: new Date(),
  });
  return { version, publication: toPublicPublication(publicationRow) };
}

// ---------------------------------------------------------------------------
// Owner resolution (group session model)
// ---------------------------------------------------------------------------

/**
 * Subject union returned by {@link resolveSiteOwnerSubject}: either the resolved
 * owner (`actorId` = the session user, `targetAgentId` = the site owner) or an
 * error with an HTTP status for the API layer to surface.
 */
export type SiteOwnerSubject =
  | { actorId: string; targetAgentId: string }
  | { error: string; status: number };

/**
 * Resolves the builder-site owner for the current session. A user always manages
 * their OWN site; managing a GROUP's site requires group-write access. Identity
 * is derived from `auth()` (via {@link resolveAuthenticatedUserId}) — never
 * client input. A requested `targetAgentId` only NAMES a group the caller may
 * manage; it is authorized via {@link hasGroupWriteAccess}, never trusted.
 */
export async function resolveSiteOwnerSubject(
  requestedTargetAgentId?: string,
): Promise<SiteOwnerSubject> {
  const actorId = await resolveAuthenticatedUserId();
  if (!actorId) {
    return { error: "You must be signed in.", status: 401 };
  }
  if (requestedTargetAgentId && requestedTargetAgentId !== actorId) {
    const allowed = await hasGroupWriteAccess(actorId, requestedTargetAgentId);
    if (!allowed) {
      return { error: "You do not manage that owner.", status: 403 };
    }
    return { actorId, targetAgentId: requestedTargetAgentId };
  }
  return { actorId, targetAgentId: actorId };
}
